-- location  ~/.wezterm.lua
-- load custom wezterm_config
--- win
-- dofile('E:/xxxxx/assets/wezterm/wezterm_config.lua')
--- mac
-- dofile('/Users/me/Documents/xxxx/assets/wezterm/wezterm_config.lua')