# Location: ~/.config/starship.toml
# https://starship.rs/config/

"$schema" = 'https://starship.rs/config-schema.json'

# https://starship.rs/config/#default-prompt-format
format = """$all$directory$character"""

# https://starship.rs/advanced-config/#enable-right-prompt
right_format = '$time$shell'

# https://starship.rs/config/#character
[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"

# https://starship.rs/config/#directory
[directory]
fish_style_pwd_dir_length = 3

# https://starship.rs/config/#shell
[shell]
disabled = false

# https://starship.rs/config/#status
[status]
disabled = false

# https://starship.rs/config/#time
[time]
disabled = false

